### PR TITLE
[WIP] Cache + pager query param fix

### PR DESCRIPTION
**Pull request by frizinak**
page 0: node/5 -> alias
page 1: node/5/1 -> no alias
page 2: node/5/2 -> no alias

to make this work with aliases will require a lot more work

resolve the alias (inbound and outbound), find the corresponding route to match against config ...

### CODE REVIEW

**Comment by frizinak** [comment]
@jelteliekens  will be testing this, so don't merge till we get his ok.

would like to get you guys' feedback on the 'aliases' stuff tthough.

**Comment by frizinak** [comment]
forgot to mention we'd also need very distinguishable page param like `my-article-page/wm-pager-1` so we can differentiate between aliases and our  param

**Comment by spoit** [comment]
Most paginating happens on custom routes (I guess) so that will still work right ( eg news/1)

That paginating won't work on aliases for taxonomy term items can become quite an issue since that can get used a lot. (news/[category]?page=2)

**Comment by jelteliekens** [comment]
@spoit That's the problem I'm having at the moment with EOS. I need to show articles on a taxonomy term page which has an alias. That's why @frizinak is proposing to use a distinguishable page param to work around this problem.

**Comment by spoit** [comment]
I'm not deep enough in it to see that we're inventing too much workarounds or that we're effectively going somewhere good here. Thoughts?

**Comment by frizinak** [comment]
This needs to happen unless we drop wmcontroller.cache (or kesh as @RobinHoutevelts has decided to name it)

The alias workaround has suddenly become secondary, as I've stumbled on an even uglier problem that seems to require a core patch: taxonomy/term/4/35?page=35. No way AFAIK to remove the query param. Drupal strikes again.

**Comment by frizinak** [comment]
Well core patch is slightly exaggerated, theme_registry_alter and copy-pasta of template_preprocess_pager would suffice, but too brute force for a friggin query param for my taste.

**Comment by frizinak** [comment]
@jelteliekens current implementations works but:

- [ ] no alias support (except for page 0)
- [ ] both a route and query param

I would go ahead and use this, while we/I try to fix both these issues, giving priority to the second one

**Comment by jelteliekens** [comment]
@frizinak I had to change the priority of the event `onAlterRoutes` to make sure the correct route is being used in `Pager`

**Comment by frizinak** [comment]
so replaced the default template_preprocess_pager which removes the need for the outbound processor but adds a ton of ugly procedural copy-pasted drupal code.

so fixing the aliases is all that remains.

**Pull request merged**
