### PR TITLE
Check if node/taxonomy exist before altering their routes

### PR DESCRIPTION
**Pull request by spoit**

### CODE REVIEW

**Comment by frizinak** [comment]
and why are we using the service locator? ffs if drupal doesnt force you to use an anti-pattern why do it anyway? Make the effort to write a constructor... (to whomever wrote this class)

also this branch should be called hotfix/...

**Comment by spoit** [comment]
@RobinHoutevelts Special reason there is no injection here? I'll fix it but there might be a reason why  it's not there

**Comment by frizinak** [comment]
I'm refactoring, gimme a sec

**Comment by RobinHoutevelts** [comment]
Originally the intent was for the consumer to write a frontcontroller.
Later it got replaced with a settings where you tell wmcontroller to look for controllers.

It should've been injected.

**Pull request closed without merging**
