### PR TITLE
Extra cache pickups

### PR DESCRIPTION
**Pull request by RobinHoutevelts**
`->setCacheMaxAge()` never worked apparantly 😊 

```php
// MyController.php
public function index()
{
    return $this->view('template')->setCacheMaxAge(60);
}
```

And

```php
// MyController.php
public function index()
{
    $foobar = $this->loadEntityFromDb();
    return $this->view(
        'template',
        [
            'foo' => $foobar, // <-- This one's cache tags werent picked up
        ]
    );
}
```

`$foobar`'s cache tags weren't picked up, unless the template did an include and passed the variable.

### CODE REVIEW

**Comment by frizinak** [comment]
## About setCacheMaxAge:

drupal is not adding the actual max-age header when u render an [#maxage => 123] array?

fixing this in the CacheSubscriber is not the correct place imo, You should call setMaxAge on the response object directly.

And defo remove the instanceof check, If I want to return my custom Response object, I want all rules to still apply.

## About the cache tags:

Hmm, yeah seems more intuitive, 

Currently dispatched tags:
main entity i.e.: the entity the current controller is 'rendering'
@include root variables

What you suggest:
main entity
all 'root' variables in a tpl.

**Comment by RobinHoutevelts** [comment]
## About setCacheMaxAge:

> drupal is not adding the actual max-age header when u render an [#maxage => 123] array?

No it doesn't :s However that might be a bug as:

```php
return [
    '#markup' => 'Hello world',
    '#cache' => [
        'max-age' => 60,
    ],
];
```

also gives me `must-revalidate, no-cache, private`. It seems like I can't set a max-age header..

> fixing this in the CacheSubscriber is not the correct place imo, You should call setMaxAge on the response object directly.

I agree working with a Response object would be a massive improvement however we don't have access to the Response object in our controllers. Our controllers still return a render array which gets transformed to an actual Response much later by Drupal ( `\Drupal\Core\EventSubscriber\MainContentViewSubscriber::onViewRenderArray` )

It doesn't look all that much trouble to put that logic in the `ViewBuilder` tho..
Seems we just need to call `\Drupal\Core\Render\MainContent\HtmlRenderer::renderResponse` with our render array.

Does this seem ok to you?

```php
return $this->view('template')
    ->createResponse()
    ->setMaxAge(60);
```

## About the cache tags:

Yes, it seems we're forgetful about the root variables that we don't `@include` later on.

**Comment by RobinHoutevelts** [comment]
> It doesn't look all that much trouble to put that logic in the ViewBuilder tho..
Seems we just need to call \Drupal\Core\Render\MainContent\HtmlRenderer::renderResponse with our render array.

Lol, didn't know you had a WIP open for just that!

**Comment by frizinak** [comment]
Right, >_>, it only uses it internally and always sets the 'no-cache' header.

I'm happy with your ResponseBuilder injected into the ViewBuilder and having a to/createResponse method.

I'd remove the setCacheMaxAge method unless we wanna stay backward compatible (which we shouldn't yet imo)  but then we'd also need to force the viewbuilder into returning a Response.

**Comment by RobinHoutevelts** [comment]
I kept `setCacheMaxAge` since it's been put in there ( https://github.com/wieni/wmcontroller/commit/b3c96dd613381cecbd2ccd73be594176a71fb7ed ) 5 months ago by jelte and I have no idea which sites use it. Marked the method as deprecated with a description on how to use the `toResponse()` method to add headers.

In the CacheSubscriber I removed the early return of the `CacheableResponse` instance check and we already made sure that max-age headers set directly on the response are prioritized.

Added a  `ResponseBuilder` service and a `toResponse()` method on the ViewBuilder.

&nbsp;


Finally I abused this PR for a request from frontend; they don't want to fill the templates with:

```twig
<script>var foo = payload|json_encode</script>
```

I added the `ViewBuilder::addDrupalSetting(string $key, $value)` method that attaches the payload to `DrupalSettings`.

```php
$payload = ['bar' => 'baz'];
return $this
    ->view('template')
    ->addDrupalSetting('foo', $payload);
```

```js
console.log(window.DrupalSettings.foo); // { bar : "baz" }
```

**Comment by frizinak** [comment]
Remove the entire CacheableResponseInterface block, it has never worked, so no point in adding it now.

Not a fan of add drupalSettings, we're on our way of defining a method for each drupal render array entry, might aswell create a RenderArrayBuilder that can recursively create render arrays

just stick to a simple template rendererer... ->&getRenderArray() perhaps and toResponse() and be done with it.

**Comment by spoit** [comment]
I think I agree with klipkens not making a method for each render array key. Better to just get the current array and add some stuff before sending..

**Comment by RobinHoutevelts** [comment]
But that was the whole point of the ViewBuilder.. To provide help in creating render arrays.

You could just do:

```php
// controller
return [
    '#theme' => 'node.article.detail'
    '#_data' => [
        'foo' => 'bar',
   ],
];
```

Which is equal to:

```php
 return $this->view('node.article.detail', [
        'foo' => 'bar',
 ]);
```

So drop ViewBuilder?

**Comment by spoit** [comment]
No the viewbuilder is Ok I think. Ok I'm confused

**Comment by frizinak** [comment]
What we want: something->render(<TplFqn>, $data); // Symfony\..\Response;

- Do we wanne stay inside of the drupal env? make the render array available
- We hate drupal? skip all that #attached / htmlHead / #cache shite and render twig directly

either way we don't need setMaxAge / set<SomePoundPropery> on whatever 'something' is.

**Comment by frizinak** [comment]
boils down to #24 #25 #26

**Comment by RobinHoutevelts** [comment]
> Do we wanne stay inside of the drupal env?
No, but that doesn't mean this module needs a feature freeze until we're rid of the drupal rendering env.

**Comment by RobinHoutevelts** [comment]
Okay removed `setCacheMaxAge()` and `addDrupalSetting()`.

My controllers now look like this:

```php
// Controller.php
public function index()
{
    $render = $this->view('index')->toRenderArray();
    $render['#attached']['drupalSettings']['foo'] = 'bar';
    return $render;
}
```

If I'd want to change the maxage they'd look like this:

```php
// Controller.php
private $responseBuilder;

public function __construct(ResponseBuilder $responseBuilder)
{
    $this->responseBuilder = $responseBuilder;
}

public function index()
{
    $render = $this->view('index')->toRenderArray();
    $render['#attached']['drupalSettings']['foo'] = 'bar';
    $response = $this->responseBuilder->createResponse($render);
    $response->setMaxAge(50);
    return $response;
}
```

If I _only_ wanted to change the maxage:

```php
// Controller.php
public function index()
{
    $response = $this->view('index')->toResponse();
    $response->setMaxAge(50);
    return $response;
}
```

---

Good enough for me.

**Comment by frizinak** [comment]
and for me ;)

we're fo sho gonna invest some time into kicking render arrays soon anyhoo.

**Comment by spoit** [comment]
I'll buy breezers then

**Pull request merged**
